---
title: "graduation_script"
author: "nick d"
date: "10/4/2015"
output: html_document
---



```{r,echo=FALSE}
library("dplyr")
```

Read in the data and subset it.

```{r, read-and-subset-data}
gap.in = read.table("output/combined_gapMinder.tsv",sep = "\t",header = TRUE)


p1 = subset(gap.in,gap.in$country == "Chad")
p2 = subset(gap.in,gap.in$country == "France")
p3 = subset(gap.in,gap.in$country == "Finland")

```

Now plot the data.

```{r, plot-data}
plot(x = p1[,2],
     y = p1[,6],
     main = paste("Year vs GDP per capita for",p1[2,1]),
    ylab = "Year",
    xlab = "GDP (USD)",
    pch = 20,
    cex = 2,
    col = "red")


plot(x = p2[,2],
     y = p2[,6],
     main = paste("Year vs GDP per capita for",p2[2,1]),
    ylab = "Year",
    xlab = "GDP (USD)",
    pch = 20,
    cex = 2,
    col = "red")

plot(x = p3[,2],
     y = p3[,6],
     main = paste("Year vs GDP per capita for",p3[2,1]),
    ylab = "Year",
    xlab = "GDP (USD)",
    pch = 20,
    cex = 2,
    col = "red")

```


```{r,aggregate data}
aggregate(gap.in$lifeExp,list(lifeExp = gap.in$lifeExp),mean)
```